# -*- coding: utf-8 -*-
"""Matplotlib_basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nRIZUCYmNuxO_FLQIJXtNsrZtHjE-OR
"""

# MATPLOTLIB SIMPLE PLOTTING
import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,3,5,7])
y=np.array([2,4,6,8])
plt.plot(x,y)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x=np.array([4,8,6,7,2,5])
y=np.array([2,7,3,9,0,6])
plt.plot(x,y,"o")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

x=np.array([4,8,6,7,2,5])
plt.plot(x)
plt.show()

# MATPLOTLIB PLOTTING WITH "MARKER"
import numpy as np
import matplotlib.pyplot as plt
x=np.array([7,2,5,0])
plt.plot(x,marker="*")
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv("IRIS.csv")
plt.plot(df["sepal_length"],df["petal_width"],"*")
plt.title("iris dataset")
plt.xlabel("petal width")
plt.ylabel("sepal length")
plt.show()

# MATPLOTLIB LINESTYLE
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv("IRIS.csv")
plt.plot(df["petal_width"],linestyle="dotted")
plt.title("iris dataset")
plt.xlabel("petal width")
plt.ylabel("sepal length")
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df=pd.read_csv("IRIS.csv")
plt.plot(df["petal_width"],color="red",label="petal width")
plt.plot(df["petal_length"],color="blue",label="petal length")

plt.legend()
plt.show()