# -*- coding: utf-8 -*-
"""matplotlib_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4RZDQ0xkjsvcgFBBfvvbpfpVomiNgCf
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df=pd.read_csv("/content/sample_data/california_housing_train.csv")
plt.plot(df["total_rooms"],color="orange",label="total_rooms")
plt.plot(df["population"],color="red",label="population")
plt.title("california housing dataset")
plt.xlabel("total_rooms")
plt.ylabel("population")
plt.legend()
plt.show()

# GRID MATPLOTLIB
plt.plot(df["households"],color="red",label="Households")
plt.plot(df["population"],color="green",label="Population")
plt.grid()
plt.title("California Housing Dataset")
plt.xlabel("Households")
plt.ylabel("Population")
plt.grid(True)
plt.legend()
plt.show()

# GRID MATPLOTLIB
plt.plot(df["households"],color="red",label="Households")
plt.plot(df["population"],color="green",label="Population")
plt.grid()
plt.title("California Housing Dataset")
plt.xlabel("Households")
plt.ylabel("Population")
plt.grid(axis="x")
plt.legend()
plt.show()

# SUBPLOT
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df=pd.read_csv("/content/sample_data/california_housing_train.csv")
plt.plot(df["longitude"], color="red", label="Longitude")
plt.plot(df["latitude"],color="green",label="latitude")
plt.subplot(2,1,1)

plt.title("California Housing Dataset")
plt.xlabel("Longitude")
plt.ylabel("Latitude")

plt.plot(df["total_rooms"],color="red")
plt.plot(df["total_bedrooms"],color="green")
plt.subplot(2,1,2)

plt.title("California Housing Dataset")
plt.xlabel("Total Rooms")
plt.ylabel("Total Bedrooms")

plt.show()

# SCATTER
plt.title("California Housing Dataset")
plt.xlabel("Households")
plt.ylabel("Population")
plt.scatter(df['households'],df['population'])
plt.show()

# SCATTER WITH "MARKER"
plt.plot(df["households"], color="red", label="Households", marker="*", linestyle="None")
plt.plot(df["population"], color="green", label="Population", marker="o", linestyle="None")

plt.title("California Housing Dataset")
plt.xlabel("Households")
plt.ylabel("Population")
plt.legend()
plt.show()

# BAR
plt.title("California Housing Dataset")
plt.xlabel("total_rooms")
plt.ylabel("Population")
plt.bar(df['total_rooms'], df['population'],color="hotpink")
plt.show()

# HISTOGRAM
plt.hist(df['households'],color="orange")
plt.title("California Housing Dataset")
plt.xlabel("Households  ")

plt.show()

# PIECHART
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x=np.array([9,5,7,3])
label_x=["apple","banana","chico","mango"]

plt.pie(x,labels=label_x)
plt.show()

plt.pie(df["households"])
plt.show()