# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-M6RdV6j4qyuLHQLPgNOeurw81dspnJ
"""

import numpy as np

# CREATION OF DIFFERENT TYPES OF ARRAYS
print(np.array([1,2,3,4]))
print(np.zeros((2,2)))
print(np.ones((2,2)))
print(np.arange(3,10))
print(np.linspace(3,8))

# ARRAY INFORMATION
a=np.array([11,22,33,44])
print("size:",a.size)
print("shape: ",a.shape)
print("no of dimention: INIT_VALUE",a.ndim)
print("datatype: ",a.dtype)
print("reshape: ",a.reshape(2,2))

# MATHEMATICAL FUNCTIONS
arr=([10,20,30,40])
print("sum: ",np.sum(arr))
print("min: ",np.min(arr))
print("max: ",np.max(arr))
print("mean: ",np.mean(arr))
print("std: ",np.std(arr))

# ARRAY OPERATION
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("addition: ",a+b)
print("subtraction: ",a-b)
print("multiplication: ",a*b)
print("Divide: ",a/b)

# COMBINING ARRAY
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.concatenate((a,b)))
print(np.hstack((b,a)))
print(np.vstack((b,a)))

a=np.array([1,2,3])
b=np.asarray([1,2,3])
print(a)
print(b)