# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFtUU0KMeGsd3URYAp9UOyzdtO-5F6IM
"""

import pandas as pd

s_data={
    "Roll_no":[1,2,3,4],
    "Name":["Aditi","Khushi","Mohini", "Riya"]
}
result=pd.DataFrame(s_data)
print(result)

series=pd.Series(s_data)
print(series)

print(s_data['Name'][1])

s_data={
    "Roll_no":[1,2,3,4],
    "Name":["Aditi","Khushi","Mohini", "Riya"]
}
labels=pd.DataFrame(s_data,index=["a","b","c","d"])
print(labels)

print(s_data["Name"])

print(result.loc[0:2])

result["Marks"]=[12,13,14,15]
print(result)

result.drop("Marks", axis=1, inplace=True, errors='ignore')
print(result)

print(result.isnull())

print(result.sort_values("Roll_no"))

print(result[result['Roll_no']>2])